version: '3.9'

services:
  server:
    image: node:18-alpine
    command: yarn run dev
    volumes:
      - .:/app
    ports:
      - 80:8080
    environment:
      - PORT=8080
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - OPENAI_API_KEY=
      - OPENAI_ORGANIZATION_ID=